### PR TITLE
Adds duration prop to modals

### PR DESCRIPTION
**Pull request by Jaywaa**
Adds prop `duration` in milliseconds before a modal hides itself.

Value of undefined or -1 naturally does not trigger a hide()

`<FadeModal ref="TaskComplete" duration={5000} />`

### CODE REVIEW

**Review by BrandonWade — APPROVED** [review]

**Comment by BrandonWade** [comment]
Looks good to me.

**Comment by Jaywaa** [comment]
Thanks for maintaining @BrandonWade. When will the latest commit be on NPM?

**Comment by BrandonWade** [comment]
I'll try and get it up later today. We're trying to get the package transferred over to us from the original owner on NPM which is taking awhile

**Comment by BrandonWade** [comment]
The new version should be available on NPM now; sorry for the delay!

**Comment by Jaywaa** [comment]
Awesome, thanks!

**Pull request merged**
